import { makeAutoObservable } from "mobx"
import { SokobanLevel } from "../models/sokoban"
import { DropdownItemProps } from "semantic-ui-react"

// const FLOOR = '-'
// const BOX = '$'
const TARGET = '.'
const BOX_TARGET = '*'
// const PLAYER = '@'
const PLAYER_TARGET = '+'

export default class SokobanStore {
    levelRegistry = new Map<string, SokobanLevel>()
    levelOptions: DropdownItemProps[] = []

    currentLevelKey = '-1'

    loadingInitial = false

    constructor() {
        makeAutoObservable(this)
    }

    get currentLevel(): SokobanLevel | undefined {
        return this.levelRegistry.get(this.currentLevelKey)
    }

    loadLevels = async () => {
        this.setLoadingInitial(true)
        try {
            const seedLevels = this.seedLevels()
            for (let i = 0; i < seedLevels.length; i++) {
                const level = this.initializeLevel(seedLevels[i]);
                this.setLevel(level)
            }
            this.setLoadingInitial(false)
        } catch (error) {
            console.log(error)
            this.setLoadingInitial(false)
        }
    }

    setCurrentLevel = (value: string) => {
        this.currentLevelKey = value
    }

    private initializeLevel = (level: SokobanLevel): SokobanLevel => {
        //initialize the level state
        level.levelState = level.initialLevel.split('/')

        //set targets
        for (let i = 0; i < level.levelState.length; i++) {
            const row = level.levelState[i];
            for (let j = 0; j < row.length; j++) {
                if (level.levelState[i][j] === TARGET) level.targets.push({ row: i, col: j })
                if (level.levelState[i][j] === BOX_TARGET) level.targets.push({ row: i, col: j })
                if (level.levelState[i][j] === PLAYER_TARGET) level.targets.push({ row: i, col: j })
            }
        }

        //set the dropdown Option
        this.levelOptions.push({
            key: '' + level.key,
            value: '' + level.key,
            text: level.title ? level.title : "Level " + level.key
        })

        return level
    }

    private setLoadingInitial = (state: boolean) => {
        this.loadingInitial = state
    }

    private setLevel = (level: SokobanLevel) => {
        this.levelRegistry.set(level.key, level)
    }

    private seedLevels = (): SokobanLevel[] => {
        let levels = this.fiftyLevels()

        for (let i = 0; i < levels.length; i++) {
            levels[i].key = (i + 1).toString();
        }

        return levels
    }

    private fiftyLevels = () => {
        const text = `###########
    #---------#
    #-$-$@$-$-#
    #--$-$-$--#
    #-$-$-$-$-#
    #--$-$-$--#
    #####$##$##
    -#.....#-#
    -#....*#-#
    -#...*---#
    -#....-###
    -########
    Title: 001 Abedlike
    Comment: Tribute to Howard Abed who made a lot of levels with this basic design. Looking through my old designs this seems to be my first original attempt at making a Sokoban puzzle.
    Previously published: Accumulated1
    Date: 2013-07-31
    
    -------######
    -####--#----#
    -#-@####-##-##
    ##-$#--#...--#
    #--$-$-#.#.#-#
    #-$-$--$...#-#
    ##-$--$-##-#-#
    -##-###----#-#
    --#---######-#
    --###--------#
    ----##########
    Title: 002 Forgotten One
    Previously published: Accumulated1
    Date: 2014-08-23
    
    ---###
    ---#.#
    ---#.#
    ####.##
    #--#.@##
    #--#.--##
    #--#.$$-#
        #-$-#$--#
        #---#-$.#
        ##-$--$-#
        -#----###
        -######
        Title: 003 My First Autogenerated Level
        Comment: Generated 50 levels. Kept one and edited a little. Not too bad.
        Previously published: Sokoban.dk(Lines), Accumulated1
        Date: 2014-10-04
        
        #########################
        #--.**.-*...$.***-..*.$-#
        #-.$-$-.$---*-$--*$-$-*-#
        #.$$-$*-*--.$.$-.-*-$-$.#
        #.$---*-*--.$.$-.-*-$-$.#
        #.$---*-*--.$.$-.-*-$-$.#
        #.$$$$*-*--.$.$-.-*-$-$.#
        #-*---$.$$--*-$--*$-$-+-#
        #-$...*-.***-.***-..*.$-#
        #########################
        Title: 004 Audi
        Comment: Looks depends on the skin.
        Previously published: SokobanOnline.com, Sokoban.dk, Accumulated1
        Date: 2014-11-08
        
        ##############################
        #--------#-----#--###--#-----#
        #--$--$-$---$--#$-##-$-$$-$--#
        #-$$######$-#-$---#----#--#$-#
        #--------#--#--#-$----##--#--#
        #--$-$-$-#$-#$-#$-#$$-##-$#$-#
        #######$-#--#-----#----#--#--#
        #--$---$-#$-$--#$-##-$-$$$$--#
        #--#-----#-----#--###--#-----#
        #-.########################$##
        #.........-----##-----#--##--#
        #........#-$$-$-#--$$-$$--#$-#
        #........#--##-$---#--#--$#--#
        #........#-$$---#-$#$-#$-$---#
        #........#-$----#$--$-#--$$--#
        #........#-$##-$----$-#--#-$-#
        #........#--$-$-#$-#--$--#---#
        #........#----@##--#--#--##--#
        ##############################
        Title: 005 Sokoban Aenigma
        Author: Brian Kent + Tyge Fogh
        Comment: Aenigma 42. Not a sharpened level, but a heavily influenced remake with several structural changes with influence on gameplay. Added 60 boxes.
        Previously published: Sokoban.dk, Accumulated1
        Date: 2014-11-09
        
        ####################
        #------------------#
        #-**$***$$***$$***-#
        #-*.-*..$-.*.-$..*-#
        #-*.-*..$-.*.-$..*-#
        #-**$***$$***$$***-#
        #----------------@-#
        ####################
        Title: 006 Not difficult. Just The Right Order
        Comment: A visual modification a year later
        Previously published: Accumulated1
        Date: 2014-11-09
        
        ---------####
        ##########--#
        #-----------#
        #-$$-$-$-$$-#
        #--#######--#
        #-$#...*.#$-#
        #--#...*.#--#
        #-$#..@$-##-#
        #--#...*.---#
        #-$#...*.#$##
        #--#######--#
        #-$$-$-$-$$-#
        #-----------#
        #############
        Title: 007 Back and Forth
        Comment: Avoiding something I had to do. 
        Previously published: SokobanOnline, Accumulated1
        Date: 2015-02-21
        
        ###########
        #----#----#
        #-.*-$-*.-#
        #-$**#**$-#
        #----+----#
        ###########
        Title: 008 Gil1
        Comment: Tried to make a level for Gil Dogans level design contest
        Previously published: Accumulated1
        Date: 2015-03-28
        
        --#####
        --#---##
        ###-#--#
        #--*-#-#
        #-*-*--#
        ##@*---#
        -#--####
        -####
        Title: 009 2x2 Cyclic
        Comment: Another level for Gil Dogans competition. I love the design and the puzzle actually took first place for a few days.
        Previously published: SokobanOnline, Accumulated1
        Date: 2015-03-28
        
        --#####
        --#---##
        ###-#--##
        #--*-#--#
        #-*-*-#-#
        #*-*-*--#
        #@*-*---#
        #--*--###
        #---###
        #####
        Title: 010 3x3 Cyclic
        Comment: Another level for Gil Dogans Sokoban contest. Here the beautifyll version. The actual level for the contest was heavily uglifyed by making til passagevay top right longer.
        Previously published: Accumulated1
        Date: 2015-03-29
        
        --#######
        --#-----#
        -##-###-##
        ##-*-@-*-##
        #-*-***-*-#
        #--*---*--#
        #---###---#
        ###-----###
        --#######
        Title: 011 Back To Start 2
        Comment: For Gil Dogans Sokoban competition. Nice, isn't it? But low scoring.
        Previously published: SokobanOnline.com, Accumulated1
        Date: 2015-04-04
        
        -----#####
        -#####---#
        ##...$---###
        #-+**##$---#
        #-..*-#-$#-#
        ##$##------#
        -#--#-$#####
        -#--$--#
        -#-----#
        -#######
        Title: 012 Upper Left Corner, Please
        Comment: Start with pushing one block to the upper left corner...
        Previously published: SokobanOnline.com, Accumulated1
        Date: 2015-04-20
        
        -#######
        -#--@--#
        -#--$--#
        ##-$.$-##
        #-$.$.$-#
        #$.$.$.$#
        #.$.$.$.#
        #-.$.$.-#
        ##-.$.-##
        -#--.--#
        -#-----#
        -#######
        Title: 013 80 Is An Okay Score
        Comment: First title was "100 Is An Okay Score" but that was too easy so changed the title.
        Previously published: SokobanOnline.com, Accumulated1
        Date: 2015-04-24
        
        ---###
        -###@###
        -#--$--#
        ##-$.$-##
        #-$.$.$-#
        #$.$.$.$#
        #.$.$.$.#
        #-.$.$.-#
        ##-.$.-##
        -#--.--#
        -###-###
        ---###
        Title: 014 Tighter
        Comment: Realised how easy the previous puzzle was.
        Previously published: SokobanOnline.com, Accumulated1
        Date: 2015-04-25
        
        -----#####
        -----#---##
        ----##-$@-#
        ---##-$*$-#
        --##...$--#
        ###-.*.-###
        #--$*..##
        #-$.$-##
        #--$-##
        #----#
        ######
        Title: 015 More Malicious
        Author: Malice+Tyge Fogh
        Comment: Thought Malicious #14 was a nice design but a little easy. This one is a little less easy, but not much.
        Previously published: SokobanOnline.com, Accumulated1
        Date: 2015-04-28
        
        --#####
        --#---##
        ###-*--##
        #--$*$--#
        #@*...*-#
        #--$*$--#
        ###-.-###
        --#---#
        --#####
        Title: 016 Lazy Saturday
        Previously published: SokobanOnline.com, Sokoban.dk, Accumulated1
        Date: 2015-05-16
        
        ---#####
        ---#---##
        -###-#--##
        ##--*-#--##
        #--*-*-#--#
        #-*-*-*-#-#
        #*-*-*-*--#
        #-*-*-*---#
        #-@*-*--###
        #---*-###
        ##---##
        -#####
        Title: 017 Back To Start 3
        Comment: I promise I will not make any bigger levels with this design. At least you will have to look in the collections Sharpen for bigger levels.
        Previously published: SokobanOnline.com
        Date: 2015-05-16
        
        ------#########
        ------##@##---#
        ------#-*-----#
        ---####---##-#####
        ---#--#-###--#---#
        ---#------#------#
        ####--#---#--##-#####
        #--##-########--#---#
        #------#-----#------#
        #--#---#-----#--##-##
        ##-#####-----#####-##
        ##-##--#-----#---#--#
        #------#-----#------#
        #---#--########-##--#
        #####-##--#---#--####
        ---#------#------#
        ---#---#--##-##--#
        ---#####-###--####
        ------#-------#
        ------#---##--#
        ------#########
        Title: 018 No challenge. Just waste of time
        Comment: Nice design but wrong size for Gil Dogans Sokoban contest.
        Previously published: SokobanOnline.com, Accumulated1
        Date: 2015-05-23
        
        ----####
        ---##--#
        ---#@*-#
        ---#-*-#
        ---#-*-#
        ---#-*-#
        ---#-*-#
        ####-*-#
        #---#*-#
        #----*-#
        ###-#--#
        -#--##-##
        -#------#
        -#--#---#
        -########
        Title: 019 Eight In A Row
        Comment: Made for Gil Dogans Sokoban Contest. A mediocre score.
        Previously published: SokobanOnline.com, Sokoban.dk(Lines), Accumulated1
        Date: 2015-06-19
        
        ------####
        ------#--#
        ------#--######
        ------#-$-----#
        ----###$#---$-#
        ----#...-###-####
        ---##.*..-#-$$--#
        ---#..##..#-----#
        ---#.*...*$$-$$##
        ---#-**#.-#-$@-#
        #####...-#-$-###
        #---####-$$--#
        #-$$$--$----##
        #----$--#--##
        #---########
        #####
        Title: 020 Not So Difficult Rev
        Comment: First version published at SokobanOnline. Discovered a ridicously easy solution. Removed a floor, added a wall, added a floor and moved the sokoban. Still no match for a trained player.
        Previously published: SokobanOnline.com., Accumulated1
        Date: 2015-06-30
        
        ######
        #----####
        #-$-.-$-#
        #-#$.$#-#
        #-..*..-#
        #-#$.$#-#
        #-$-+-$-#
        #####---#
        ----#####
        Title: 021 Summer 1
        Previously published: SokobanOnline.com, Sokoban.dk (Crosses), Accumulated1
        Date: 2015-07-02
        
        ###########
        #...------#
        #######-#-#
        #.------#-#
        #.$$$$#-#-#
        #.----$-#-#
        #$#######-#
        #@--------#
        ###########
        Title: 022 Timesaver
        Comment: Same basic design as level 59 from TIAOAs first collection. Saves you a lot of time.
        Previously published: Sokoban.dk, Accumulated1
        Date: 2015-07-04
        
        ---------####
        -#########--#
        ##--$-----.-##
        #--$-$-#-***-#
        #@$-$-$#..*..#
        ##-$-$-#-...-#
        -#--$--##-.--#
        -##--#########
        --####
        Title: 023 Summer 2
        Comment: Variation from SokobanOnline.com. Made the right side a bit more interesting.
        Previously published: SokobanOnline.com, Accumulated1.
        Date: 2015-07-03
        
        -----#####
        -----#---#
        --####-#-##
        --#----*--##
        ###-#-*.*--#
        #---#.$#-*-#
        #---*-*-*-*#
        ######-$-#-#
        -----#-@---#
        -----#######
        Title: 024 Pyramid
        Comment: Rotated the puzzle 90 deg. clockwise for my collection "Go Right"
        Previously published: SokobanOnline.com, Sokoban.dk(Go Right), Accumulated1.
        Date: 2015-07-11
        
        ----####
        ----#--#
        ----#--#
        --###--#
        ###--*-##
        #---*-*-###
        #--*-*-*--#
        ###-*-*---#
        --##-*-####
        ---#--##
        ---#-@#
        ---####
        Title: 025 Less Pain
        Comment: Needed an easy one after publishing a remodel from Gil Dogans contest.
        Previously published: SokobanOnline.com, Accumulated1.
        Date: 2015-07-14
        
        ---#
        --###
        -##-##
        ##-.-##
        #--*--#
        #--*--#
        #-$*$##
        ##-*-##
        -#-*-#
        -#-*-#
        -#-*-#
        -#-.-#
        -#-@-#
        -#####
        Title: 026 No Pain
        Previously published: SokobanOnline.com, Sokoban.dk(Lines), Accumulated1.
        Date: 2015-07-14
        
        ##########
        #--------#
        #-*.*.*..#
        ##$####-##
        #--$@$-$-#
        #--------#
        ##########
        Title: 027 An In Betweener With No Title Originally
        Previously published: Sokoban.dk(Lines) Accumulated1.
        Date: 2015-08-02
        
        #############
        #------.....#
        #------*.*..#
        #--######-#$###
        #--#--$-$---$-#
        #--#-$#-#-#-#-#
        ####--$---$-$-#
        ---##@#######-#
        ---#----------#
        ---############
        Title: 028 No Pain 2 Rev
        Comment: Just added a wall to the puzzle originally published at SokobanOnline. Not sure it makes a more interesting puzzle.
        Previously published: SokobanOnline.com, Accumulated1.
        Date: 2015-08-10
        
        ---#####
        ---#---##
        -###-#--##
        -#--*-#--##
        ##-#-*-#--#
        #---*-*-#-#
        #@-*-*-*--#
        ##--*---###
        -#####--#
        -----####
        Title: 029 Last One For Free
        Comment: Published 25 levels on SokobanOnline.com. Had to pay 0.99$ for an upgrade to pro memeber to publish more. But the site gave me a free ticket.
        Previously published: SokobanOnline.com, Accumulated1.
        Date: 2015-08-10
        
        ---#####
        --##---#
        -##--#-###
        ##--#-*--##
        #--#-*-*--#
        #-#-*-*-*-###
        #--*-#-#-*--#
        ##--*-*-*---#
        -##--*-*---##
        --##--*--@##
        ---########
        Title: 030 Back To Start 44 Variation
        Comment: Could be a plain 4x4 cyclic puzzle. But you dont need to move all the blocks in many cyclic puzzles. The trick is to figure out which ones
        Previously published: Accumulated1.
        Date: 2015-08-11
        
        -------#####
        ########---##
        #--##--$$---#
        #--------#$-#
        #-$##-#--#-###
        ##-#--####---#
        -#-#-#.-.#*#-#
        -#-#-#.*.*.#-#
        -#--$$-#-.*-@#
        -#---####---##
        -#--##--#####
        -####
        Title: 031 Not 6x2
        Comment: Wanted to make a level with a 6*2 goal. Ended up like this.
        Previously published: SokobanOnline.com, Accumulated1.
        Date: 2015-08-15
        
        --#########
        --#---.---#
        --#---.---#
        --#-##.####
        --#-#-.---###
        ###-#-.-#---#
        #-$$$$*$$$$-#
        #---#-.-#---#
        ###--#.-#####
        --##--+##
        ---#####
        Title: 032 Nine In A Row
        Previously published: SokobanOnline.com, Sokoban.dk(Lines), Accumulated1.
        Date: 2015-08-19
        
        ####-####
        #--###--#
        #--$----#
        #-$#.#--#
        ##--.#-##
        -#$#.#-#
        -#--.#-#
        -#$#.#-##
        -#---#--#
        -#$----@#
        -#--#####
        -####
        Title: 033 Five In A Row
        Previously published: SokobanOnline.com, Sokoban.dk(Lines), Accumulated1.
        Date: 2015-08-22
        
        --#####
        --#---#
        ###---###
        #--***--#
        #--*@*--#
        ###***--#
        --#---###
        --#---#
        --#####
        Title: 034 Nice And Not So Easy
        Comment: Checked nobody ever made this puzzle before.
        Previously published: SokobanOnline.com, Accumulated1.
        Date: 2015-08-24
        
        --######
        --#----#
        ###--#-###
        #--****--#
        #--*@-*--#
        #--*--*--#
        ##########
        Title: 035 Page Two
        Comment: A beautiful simple design. A favorite of mine.
        Previously published: SokobanOnline.com, Accumulated1.
        Date: 2015-08-25
        
        ----------#
        ----------##
        ----------###
        ----------#-##
        ###########--##
        #-------------##
        #.**********$--##
        #--------@---###
        ###########--##
        ----------#-##
        ----------###
        ----------##
        ----------#
        Title: 036 Next
        Comment: You can find 100.000+ sokoban levels on the net and still nobody ever made this simple design. Amazing.
        Previously published: SokobanOnline.com, Sokoban.dk(Go Right), Accumulated1.
        Date: 2015-09-05
        
        ---####
        ####--####
        #-$-.*-$-#
        #-#-**-#-#
        #-#-..-#-#
        #---##$--#
        ###--@-###
        --######
        Title: 037 2x3
        Comment: Idea from David Hollands Maelstrom 18.
        Previously published: Accumulated1.
        Date: 2015-09-10
        
        -----#######
        -----#-----##
        -----#-.----#
        -######.#-#-#
        ##---##.#---#
        #---$-#.#---#
        #-$$$-#.#---#
        #--@$-#.----#
        #-$#$--.#---#
        #---$-#.#####
        #####---#
        ----#####
        Title: 038 Elegance
        Comment: An elegant unexpected solution just popped out.
        Previously published: Sokoban.dk(Lines) Accumulated1.
        Date: 2015-09-22
        
        -#######
        -#-----#
        ##$#-#$####
        #--.....*-#
        #-#$##$#$-#
        #------#--#
        ###-#@##-##
        --#------#
        --########
        Title: 039 An Easy Six
        Comment: Wont keep you sleepless.
        Previously published: Accumulated1.
        Date: 2015-09-27
        
        #########
        #---#---#
        #-#---#-#
        #-$$.$$@#
        ##..*..##
        #-$-.---#
        #-#-#$#-#
        #---#---#
        #########
        Title: 040 5x3
        Previously published: Accumulated1.
        Date: 2015-10-03
        
        ------#
        -----###
        ------#
        -----###
        ----##.##
        ---##.$.##
        --##-$.$-##
        -##-.-$-.-##
        ##-*-.#.-*-##
        #-$-*###*-$-#
        #--$--#--$--#
        #-----#--@--#
        #############
        Title: 041 Happy Christmas
        Comment: Idea from "Prayers" by Bodler. Added a cross on top and published at SokobanOnline 2015-12-24 with the title "Happy Christmas"
        Previously published: SokobanOnline.com, Sokoban.dk(Remodels1), Accumulated1.
        Date: 2015-10-03
        
        -----#####
        -----#---#
        ----##-#-##
        ----#-----#######
        ----#-----#-----#
        ----#-##.##-$-#-#
        ---##--#.####$--#
        -#####-#....$-$-#
        ##---#....##-$--#
        #----#$##.##$##-#
        #-$----$-*-#@---#
        #-#---$----######
        #-#####$####
        #-------#
        #########
        Title: 042 Whatever
        Comment: Decided to do something with a crossshaped goal.
        Previously published: Sokoban.dk (Crosses), DrFogh-Accumulated 1
        Date: 2014-10-05
        
        --#####
        --#-.-#
        --#$.$#
        --#-.-#
        --#-.-#
        ###$.$###
        #--$.$--#
        #---*---#
        ###-@-###
        --#####
        Title: 043 So Simple 1
        Comment: And still never made before.
        Previously published: SokobanOnline.com
        Date: 2015-10-10
        
        --#####
        --#-.-#
        --#$.$#
        --#-.-#
        --#$.$#
        --#-.-#
        --#-.-#
        ###$.$###
        #--$.$--#
        #---*---#
        ###-@-###
        --#####
        
        Title: 044 So Simple 2
        Comment: A little higher
        Date: 2015-10-10
        
        --#####
        --#-.-#
        --#$.$#
        --#-.-#
        --#$.$#
        --#-.-#
        --#$.$#
        --#-.-#
        --#$.$#
        --#-.-#
        --#-.-#
        ###$.$###
        #--$.$--#
        #---*---#
        ###-@-###
        --#####
        Title: 045 So Simple 4
        Comment: This design can be expanded infinitely. From this puzzle and further YASS couldn't solve it.
        Previously published: Sokoban.dk(Lines)
        Date: 2015-11-13
        
        --------#####
        #########---#
        #----.....#-#
        #---@$------#
        ##-#######-##
        -#-----#--$#
        -###-#$#---#
        ---#---$-$##
        ---####---#
        -----######
        Title: 046 Row514
        Comment: The title? Goal five in a row. Layout no 14 was final level.
        Previously published: Sokoban.dk(Lines)
        Date: 2015-09-25
        
        ----#####
        ----#---#
        ----#$.$#
        ----#-.-#
        #####$.$#####
        #-$-$-.-$-$-#
        #-....@....-#
        #-$-$-.-$-$-#
        #####$.$#####
        ----#-.-#
        ----#$.$#
        ----#-.-#
        ----#$.$#
        ----#-.-#
        ----#$.$#
        ----#---#
        ----#####
        Title: 047 Cross
        Previously published: SokobanOnline.com, Sokoban.dk (Crosses)
        Date: 2015-10-18
        
        46 Cross. Now With Centerblock
        
        ----#####
        ----#---#
        ----#$.$#
        ----#-.-#
        #####$.$#####
        #-$-$-+-$-$-#
        #-....*....-#
        #-$-$-.-$-$-#
        ####-$.$-####
        ---##-.-##
        ----#$.$#
        ----#-.-#
        ----#$.$#
        ----#-.-#
        ----#$.$#
        ----#---#
        ----#####
        Title: 048 Cross. Now With Centerblock
        Previously published: SokobanOnline.com, Sokoban.dk (Crosses)
        Date: 2015-10-18
        
        #########
        #--.-.--#
        #--$-$--#
        ##*****##
        #--$-$--#
        #--.@.--#
        #########
        Title: 049 Nakarev
        Comment: Thought it was inspiration from Nakaxsomething, but it was somewhere else.
        Previously published: SokobanOnline.com
        Date: 2015-11-12
        
        --------#####
        --------#---##
        --#####-#-$--#
        --#---####-#-###
        --#-#...-$--$--#
        ###-#.#.#$$$-#-#
        #---#...#-#----#
        #-#-#...#-#$$###
        #----...#@$---#
        ######-##$$---#
        -----#--#-##-##
        -----#-$#-$--#
        -----#--$---##
        -----##---###
        ------#####
        Title: 050 Dev42
        Previously published: Sokoban.dk
        Date: 2015-11-19`

        const formattedData = []
        let currentLevel: string = ""

        const lines = text.split('\n');
        let tooLong = false

        for (let i = 0; i < lines.length; i++) {
            const line = lines[i].trim()

            //level lines conclude with the 'Title'
            if (line.startsWith('Title')) {
                if (currentLevel.length > 0 && !tooLong) {
                    let level: SokobanLevel = {
                        title: line.substring(7),
                        key: '-1',
                        initialLevel: currentLevel,
                        levelState: [],
                        targets: []
                    }
                    formattedData.push(level)
                    console.log(formattedData.length + ":", level);
                    currentLevel = ""
                }
                if (tooLong) {
                    currentLevel = ""
                    tooLong = false
                }
            }

            // If its a level line, add it to the currentLevel
            if (line.length > 0
                && !line.startsWith('Title')
                && !line.startsWith('Comment')
                && !line.startsWith('Previously')
                && !line.startsWith('Date')) {
                if (line.length > 16) tooLong = true //only 16 columns right now
                if (currentLevel.length > 0) currentLevel += '/'
                currentLevel += line
            }
        }
        return formattedData
    }
}